name: "epinow2"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  generate-forecasts:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Generate forecasts
      working-directory: models/${{ github.workflow }}
      run: |
        bash main.sh
      
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.workflow }}
        retention-days: 5
        path: models/${{ github.workflow }}/data-processed/**

  upload-forecasts:
    needs: generate-forecasts
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with: 
        repository: 'epiforecasts/covid19-forecast-hub-europe'
        token: ${{ secrets.EPIFORECASTS_TOKEN }}
    
    - uses: actions/download-artifact@v2
      with:
        name: ${{ github.workflow }}
        path: data-processed
        
    - uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e
      id: cpr
      with:
        token: ${{ secrets.EPIFORECASTS_TOKEN }}
        commit-message: ${{ github.workflow }}'s automated submission
        committer: epiforecasts-bot <epiforecasts-bot@users.noreply.github.com>
        author: epiforecasts-bot <epiforecasts-bot@users.noreply.github.com>
        branch: ${{ github.workflow }}
        title: ${{ github.workflow }}'s automated submission
        body: Automated submission via https://github.com/epiforecasts/covid19-forecast-hub-europe-submissions
        delete-branch: true

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
